apiVersion: v1
kind: Service
metadata:
  name: smartrecipe-backend
  labels:
    app.kubernetes.io/name: smartrecipe-backend
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    app.kubernetes.io/name: smartrecipe-backend
