classDiagram
    direction TB

    class Anna {
        <<object>>
        +email = "anna.k@example.com"
    }

    class PestoPasta {
        <<object>>
        +title = "Makaron z pesto"
        +lifecycleStatus = ACTIVE
    }

    class Pasta {
        <<object>>
        +quantity = 400
        +unit = "g"
    }

    class Pesto {
        <<object>>
        +quantity = 2
        +unit = "lyzki"
    }

    class IngSpaghetti {
        <<object>>
        +name = "Makaron spaghetti"
    }

    class IngBasilFresh {
        <<object>>
        +name = "Liscie bazylii"
    }

		class IngGarlicFresh {
        <<object>>
        +name = "Czosnek swiezy"
    }

		class IngPiniaNuts {
        <<object>>
        +name = "Orzeszki pinii"
    }

    class PantryPasta {
        <<object>>
        +quantity = 500
        +unit = "g"
    }

    class PantryOliveOil {
        <<object>>
        +quantity = 200
        +unit = "ml"
    }

    Anna --> PestoPasta : wlasciciel_przepisu
    PestoPasta --> Pasta : wymaga
    PestoPasta --> Pesto : wymaga
    Pasta --> IngSpaghetti : skladnik
    Pesto --> IngBasilFresh : skladnik
    Pesto --> IngGarlicFresh : skladnik
    Pesto --> IngPiniaNuts : skladnik

    Anna --> PantryPasta : ma_w_spizarni
    Anna --> PantryOliveOil : ma_w_spizarni
    PantryPasta --> IngSpaghetti : ten_sam_skladnik