graph LR
    User(("A01\nUżytkownik"))
    NutAPI(["A02\nZewnętrzne API\nŻywność"])
    RecAPI(["A03\nZewnętrzne API\nPrzepisy"])
    DeeplAPI(["A04\nDeepL API\nTłumaczenie"])

    subgraph sys["System SmartRecipe"]
        UC01("UC01\nZarządzanie przepisami")
        UC02("UC02\nZarządzanie spiżarnią")
        UC03("UC03\nGenerowanie propozycji\nposiłków")
        UC04("UC04\nZarządzanie listą\nzakupów")
        UC05("UC05\nWyszukiwanie\nprzepisów zewnętrznych")
    end

    User --- UC01
    User --- UC02
    User --- UC03
    User --- UC04
    User --- UC05
    UC01 -. "<<uses>>" .-> DeeplAPI
    UC01 -. "<<uses>>" .-> NutAPI
    UC03 -. "<<uses>>" .-> NutAPI
    UC05 -. "<<uses>>" .-> RecAPI
    UC04 -. "<<extend>>" .-> UC02
