apiVersion: v1
kind: Service
metadata:
  name: smartrecipe-postgres
  labels:
    app.kubernetes.io/name: smartrecipe-postgres
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    app.kubernetes.io/name: smartrecipe-postgres
